[package]
name = "coco-futhark"
version = "0.1.0"
edition = "2021"

[features]
c = []
multicore = []
opencl = []
cuda = []
default = ["c"]

[build-dependencies]
bindgen = "0.65.1"
cc = "1.0.79"
eyre = "0.6.8"
rerun_except = "1.0.0"
