[package]
name = "coco-accelerated"
version = "0.1.0"
edition = "2021"

[features]
opencl = ["coco-futhark/opencl"]
multicore = ["coco-futhark/multicore"]

[dependencies]
coco = { version = "0.5.0", package = "coco-rs" }
coco-futhark = { path = "../coco-futhark" }
coco-legacy = { path = "../coco-legacy" }
float_eq = "1.0.0"

[dev-dependencies]
criterion = "0.3.5"
once_cell = "1.12.0"
proptest = "1.0.0"
